name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  IMAGE_NAME: waelhlali21/docker_push:tagname
  DEPLOYMENT_NAME: dockrep
  PORT: 5000 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker_push
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: nourch29
          password: ${{secrets.DOCKERHUB_PASS}}
          repository: nourch29/dockrep
          tag_with_ref: true
          
      
